### ISSUE TITLE
Should not display red notification badge when unread count is 0

### ISSUE THREAD

**Issue by sneak** [elgatosf/streamdeck-applemail#1]

**Comment by Timac** [comment]
Thanks for reporting this problem. The new version 1.4 of this plugin fixes this issue. The plugin is also live in the Stream Deck store.

**Comment by sneak** [comment]
I installed the latest Stream Deck app and installed the Apple Mail extension from the store yesterday and I've still got a bright red 0 badge, so something in the pipeline is wrong unless it's been released in the last 12 hours.

**Comment by sneak** [comment]
Thank you!  That's an impressive turnaround time!
